const PRODUCTS = [
  {
    id: "p1",
    name: "1 Gram Gold Maharashtrian Kolhapuri Saaj",
    category: "1-gram-gold",
    type: "necklace",
    price: 4999,
    originalPrice: 7499,
    rating: 4.9,
    reviews: 124,
    image: "assets/images/cat_traditional.png",
    description: "An exquisite traditional Maharashtrian Kolhapuri Saaj crafted in premium 1 gram gold finish. Adorned with hand-carved leaves detailing standard Maharashtrian heritage.",
    isBestseller: true,
    isTraditional: true
  },
  {
    id: "p2",
    name: "Royal Bridal Kundan Choker Set",
    category: "bridal",
    type: "necklace",
    price: 15999,
    originalPrice: 24999,
    rating: 5.0,
    reviews: 86,
    image: "assets/images/bridal_showcase.png",
    description: "Make your special day unforgettable with this premium royal kundan choker set, complete with matching earrings and maang tikka. Coated in heavy luxury gold plating.",
    isBestseller: true,
    isTraditional: true
  },
  {
    id: "p3",
    name: "Sterling Silver Solitaire Eternity Ring",
    category: "silver",
    type: "ring",
    price: 2499,
    originalPrice: 3999,
    rating: 4.8,
    reviews: 95,
    image: "assets/images/cat_silver.png",
    description: "A breathtaking sterling silver eternity ring featuring brilliant cut simulated diamonds that sparkle from every angle. Elegant, simple, and everlasting.",
    isBestseller: true,
    isDailywear: true
  },
  {
    id: "p4",
    name: "Traditional Gold Plated Laxmi Haar",
    category: "gold-plated",
    type: "necklace",
    price: 6999,
    originalPrice: 9999,
    rating: 4.9,
    reviews: 74,
    image: "assets/images/cat_1gram.png",
    description: "A grand temple-style Laxmi Haar with intricate engravings of Goddess Lakshmi. Perfect for weddings, festivals, and traditional Maharashtrian events.",
    isBestseller: false,
    isTraditional: true
  },
  {
    id: "p5",
    name: "1 Gram Gold Traditional Thushi",
    category: "1-gram-gold",
    type: "necklace",
    price: 3499,
    originalPrice: 4999,
    rating: 4.7,
    reviews: 142,
    image: "assets/images/cat_traditional.png",
    description: "A classic Maharashtrian choker style necklace featuring closely packed gold beads. Made with 1 gram gold plating and adjustable thread dori.",
    isBestseller: true,
    isTraditional: true
  },
  {
    id: "p6",
    name: "Sleek Daily Wear Gold Bangle Set",
    category: "gold-plated",
    type: "bangles",
    price: 2999,
    originalPrice: 4499,
    rating: 4.8,
    reviews: 110,
    image: "assets/images/cat_dailywear.png",
    description: "A set of four sleek gold-plated bangles designed for daily wear. Resilient shine, lightweight, and extremely comfortable for everyday elegance.",
    isBestseller: true,
    isDailywear: true
  },
  {
    id: "p7",
    name: "Sterling Silver Floral Drop Earrings",
    category: "silver",
    type: "earrings",
    price: 1899,
    originalPrice: 2999,
    rating: 4.6,
    reviews: 63,
    image: "assets/images/cat_silver.png",
    description: "Crafted in 92.5 sterling silver, these delicate floral drop earrings add a touch of modern luxury and grace to both western and traditional outfits.",
    isBestseller: false,
    isDailywear: true
  },
  {
    id: "p8",
    name: "Gold Plated Peacock Jhumkas",
    category: "gold-plated",
    type: "earrings",
    price: 1999,
    originalPrice: 2999,
    rating: 4.9,
    reviews: 215,
    image: "assets/images/cat_goldplated.png",
    description: "Stunning peacock motif jhumka earrings featuring ruby red stones and delicate hanging gold bead drops. A timeless classic for festive wear.",
    isBestseller: true,
    isTraditional: true
  },
  {
    id: "p9",
    name: "Luxury Gold Plated Wati Mangalsutra",
    category: "1-gram-gold",
    type: "mangalsutras",
    price: 2799,
    originalPrice: 3999,
    rating: 4.9,
    reviews: 189,
    image: "assets/images/cat_traditional.png",
    description: "The traditional double-wati pendant strung on black beads and gold-plated chain. Symbol of marital trust and everlasting elegance.",
    isBestseller: true,
    isTraditional: true
  },
  {
    id: "p10",
    name: "Sleek Gold Plated Daily Wear Chain",
    category: "gold-plated",
    type: "chains",
    price: 1499,
    originalPrice: 2499,
    rating: 4.7,
    reviews: 320,
    image: "assets/images/cat_dailywear.png",
    description: "A classic link-style daily wear chain designed to withstand daily activity without losing its rich gold shine. Includes sturdy S-hook clasp.",
    isBestseller: false,
    isDailywear: true
  },
  {
    id: "p11",
    name: "Premium Silver Oxidized Choker",
    category: "silver",
    type: "necklace",
    price: 3299,
    originalPrice: 4999,
    rating: 4.8,
    reviews: 54,
    image: "assets/images/cat_silver.png",
    description: "A gorgeous, high-end oxidized silver choker with intricate floral and tribal motifs, perfect for fusion wear and festive occasions.",
    isBestseller: false,
    isTraditional: true
  },
  {
    id: "p12",
    name: "Maharashtrian Bridal Pearl Nath",
    category: "bridal",
    type: "earrings",
    price: 1299,
    originalPrice: 1999,
    rating: 4.9,
    reviews: 167,
    image: "assets/images/bridal_showcase.png",
    description: "Classic Maharashtrian nose-ring (Nath) studded with premium pearls, pink stones, and a single green bead. Easy press-on wear, no piercing required.",
    isBestseller: false,
    isTraditional: true
  }
];

const CATEGORIES = [
  { id: "1-gram-gold", name: "1 Gram Gold Jewellery", count: 3, image: "assets/images/cat_1gram.png" },
  { id: "gold-plated", name: "Gold Plated Jewellery", count: 4, image: "assets/images/cat_goldplated.png" },
  { id: "silver", name: "Silver Jewellery", count: 3, image: "assets/images/cat_silver.png" },
  { id: "bridal", name: "Bridal Collection", count: 2, image: "assets/images/bridal_showcase.png" },
  { id: "traditional", name: "Traditional Collection", count: 5, image: "assets/images/cat_traditional.png" },
  { id: "daily-wear", name: "Daily Wear Collection", count: 4, image: "assets/images/cat_dailywear.png" }
];
